require("setting")
require("navigate")
require("function")
require("pluggin")
require("variable")
require("keymap")
require("keyua")
require("treeseater")
require("autocmd")
vim.cmd('colorscheme tender')
