require("setting")
require("navigate")
require("pluggin")
require("variable")
require("keymap")
require("keyeng")
require("treeseater")
require("filetype")
require("snippet")
vim.cmd('colorscheme tender')
