require("setting")
require("navigate")
require("function")
require("pluggin")
require("variable")
require("keymap")
require("keyeng")
require("treeseater")
require("cmd")
vim.cmd('colorscheme tender')
