vim.g.coc_global_extensions = {
  'coc-tsserver',
  'coc-json',
  'coc-eslint',
  'coc-pairs',
  'coc-css',
  'coc-cssmodules',
  'coc-stylelintplus',
  'coc-html',
  'coc-htmlhint',
  'coc-emmet',
  'coc-snippets',
  'coc-spell-checker',
  'coc-webpack',
  'coc-svg',
  'coc-xml',
  'coc-vetur',
}
