alias nv="nvim"
alias wge="sudo systemctl status wg-quick@wg0.service"
alias wgeon="sudo systemctl start wg-quick@wg0.service"
alias wgeoff="sudo systemctl stop wg-quick@wg0.service"
alias cl="clear"
alias seten="setxkbmap -layout us ; sleep 0.5s ; setxkbmap -layout 'us,ua' -option ',winkeys' -option 'grp:alt_shift_toggle'"
alias d="docker"
